# -*- coding: utf-8 -*-
"""Final_Paint Control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DyOoTVu1ok8cn_bFoF8FxAcQ0uFkCPQ
"""

import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split as tts
from keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler
import keras.backend as K
import warnings
warnings.simplefilter(action='ignore')

df =  pd.read_csv("/content/drive/MyDrive/Dataset for TCP/Preprocessed Dataset for LSTM/paintcontrol_priority.csv")
df.shape

df.head()

import seaborn as sns

# Select specific features
selected_features = ['DurationFeature', 'TimeSinceLastRun', 'FailureCount', 'PassCount', 'change_in_status', 'E1', 'E2', 'E3', 'Anomaly_Score']

# Calculate the correlation matrix using Pearson correlation coefficient for the selected features
correlation_matrix = df[selected_features].corr(method='pearson')

# Plot the correlation matrix as a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title('Correlation Matrix on Paint Control')
plt.show()

def soft_acc(y_true, y_pred):
    return K.mean(K.equal(K.round(y_true), K.round(y_pred)))

X = df[['DurationFeature', 'TimeSinceLastRun', 'FailureCount', 'PassCount', 'change_in_status', 'E1', 'E2', 'E3', 'Anomaly_Score']] # Defining feature variable
y = df['Verdict'] # Defining label variable
MSE_list=[] # mean square error list
R2_list=[]

def split_dataset():
    # splitting dataset, 80% training and 20% testing
    X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=42)

    # Scaling both training and testing input data.
    data_scaler = MinMaxScaler()
    X_train = data_scaler.fit_transform(X_train)
    X_test = data_scaler.transform(X_test)

    return X_train, X_test, y_train, y_test

def prediction_function(X_train,X_test):

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    return y_test_pred

X_train, X_test, y_train, y_test = split_dataset()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Define LSTM model with dropout
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(X_train.shape[1], 1)))
model.add(Dropout(0.2))  # Adjust the dropout rate as needed
model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(Dropout(0.2))  # Adjust the dropout rate as needed
#model.add(LSTM(50, activation='relu', return_sequences=True))
#model.add(Dropout(0.2))  # Adjust the dropout rate as needed
model.add(LSTM(50, activation='relu'))
model.add(Dropout(0.2))

# Add dense layers
#model.add(Dense(128, activation='relu'))  # First dense layer
model.add(Dense(32, activation='relu'))  # Second dense layer
model.add(Dense(16, activation='relu'))  # Third dense layer

# Final output layer
model.add(Dense(1))

# Print model summary
print(model.summary())

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=[soft_acc])

# Train the model with early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=50, restore_best_weights=True)

# Train the model
history = model.fit(X_train, y_train, epochs=500, batch_size=32, validation_data=(X_test, y_test), callbacks=[early_stopping])

model.evaluate(X_test, y_test)

model.evaluate(X_train, y_train)

from matplotlib import pyplot
pyplot.plot(history.history['loss'], label='Train')
pyplot.plot(history.history['val_loss'], label='Test')
pyplot.xlabel('Epochs',fontsize=22)
pyplot.ylabel('Loss',fontsize=22)
pyplot.title('Loss Curve',fontsize=22)
pyplot.legend()
pyplot.show()

# Plot accuracy curve
pyplot.plot(history.history['soft_acc'], label='Train')
pyplot.plot(history.history['val_soft_acc'], label='Test')
pyplot.xlabel('Epoch',fontsize=22)
pyplot.ylabel('Loss',fontsize=22)
pyplot.title('Accuracy Curve',fontsize=22)
pyplot.legend()
pyplot.show()

from sklearn.base import BaseEstimator
from sklearn.inspection import permutation_importance

class KerasEstimator(BaseEstimator):
    def __init__(self, model):
        self.model = model

    def fit(self, X, y):
        pass

    def predict(self, X):
        return self.model.predict(X)

# Create the custom estimator
estimator = KerasEstimator(model)

# Calculate permutation importance
perm_importance = permutation_importance(estimator, X_test, y_test, scoring='neg_mean_squared_error', n_repeats=10, random_state=42)

# Extract feature importance scores
importance_scores = perm_importance.importances_mean

# Normalize importance scores
normalized_importance_scores = importance_scores / np.sum(importance_scores)

# Print or visualize the importance scores
print("Feature Importance Scores:", normalized_importance_scores)

# Use the trained model to predict priority values
predicted_priority = model.predict(X_test)

# Print all predicted priority values
#for priority_value in predicted_priority:
 #   print(priority_value)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Calculate R^2
r2 = r2_score(y_test, predicted_priority)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, predicted_priority)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, predicted_priority)

# Calculate Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)

print("R^2:", r2)
print("MSE:", mse)
print("MAE:", mae)
print("RMSE:", rmse)

from datetime import datetime
# Define the start time before starting the prioritization process
start_prio_time = datetime.now()

data_scaler = MinMaxScaler()

start_prio_time = datetime.now()
data_scaler = MinMaxScaler()
XX = data_scaler.fit_transform(df[['DurationFeature', 'TimeSinceLastRun', 'FailureCount', 'PassCount', 'change_in_status', 'E1', 'E2', 'E3', 'Anomaly_Score']])
A = model.predict(XX)
df['CalcPrio'] = A
df.head()
final_df = df.sort_values(by=['CalcPrio'], ascending=False)
final_df['ranking'] = range(1, 1+len(df))
available_time = sum(final_df['Duration'])
prioritization_time = datetime.now() - start_prio_time

final_df.head(5)

values = pd.DataFrame()
values['Id'] =  range(0, 1)
values['env'] = 'iofrol'

# m is number of fault in dataset
_,m=df['Verdict'].value_counts()
n=df.shape[0]
values['Number of Failed Tests'] = m
values['Total Test Cases'] = n

scheduled_time = 0
detection_ranks = []
undetected_failures = 0
rank_counter = 1

for index, row in final_df.iterrows():
    if scheduled_time + row['Duration'] <= available_time:
        if row['Verdict'] == 1:
            detection_ranks.append(rank_counter)
        scheduled_time += row['Duration']
        rank_counter += 1
    else:
        undetected_failures += row['Id']

detected_failures = len(detection_ranks)

p = 0
if undetected_failures > 0:
    p = (detected_failures / m)
else:
    p = 1
print ("recall: ",p)

if p==1:
    apfd = p - sum(detection_ranks) / (m * n) + p / (2 * n)
    print ("apfd: ",apfd)
    print ("napfd equals apfd")
else:
    napfd = p - sum(detection_ranks) / (m * n) + p / (2 * n)
    print ("napfd: ",napfd)

values['APFD'] = apfd

import warnings
warnings.simplefilter(action='ignore')
missing = []
Last_cycle = df['Cycle'].iloc[-1]
print(Last_cycle, " will be last cycle")
scheduled_testcases = pd.DataFrame()
i = 1
NAPFD = []
prev_cycle = 0
for index in range(1, Last_cycle):
    if i <= Last_cycle and i in df['Cycle']:
        df_temp = df.loc[df['Cycle'] == (i)]
        i = i + 1
        if df_temp.empty:
            missing.append(i - 1)
            continue
        XX = data_scaler.fit_transform(df_temp[['DurationFeature', 'TimeSinceLastRun', 'FailureCount', 'PassCount', 'change_in_status', 'E1', 'E2', 'E3', 'Anomaly_Score']])
        A = model.predict(XX)
        df_temp['CalcPrio'] = A
        final_df_temp = df_temp.sort_values(by=['CalcPrio'], ascending=False)
        available_time = sum(final_df_temp['Duration'])
        counts = final_df_temp['Verdict'].value_counts().to_dict()
        m = counts.get(1, 0)
        n = final_df_temp.shape[0]
        scheduled_time = 0
        detection_ranks = []
        undetected_failures = 0
        rank_counter = 1
        for index, row in final_df_temp.iterrows():
            if scheduled_time + row['Duration'] <= available_time:
                if row['Verdict'] == 1:
                    detection_ranks.append(rank_counter)
                scheduled_time += row['Duration']
                rank_counter += 1
            else:
                undetected_failures = undetected_failures + 1
        detected_failures = len(detection_ranks)
        if m > 0:
            p = 0
            if undetected_failures > 0:
                p = (detected_failures / m)
            else:
                p = 1
            if (m == 1 and n == 1):
                NAPFD.append(1)
            elif p == 1:
                apfd = p - sum(detection_ranks) / (m * n) + p / (2 * n)
                NAPFD.append(apfd)
            else:
                napfd = p - sum(detection_ranks) / (m * n) + p / (2 * n)
                NAPFD.append(napfd)
        else:
            NAPFD.append(0)

# Print all NAPFD values with different cycles
print("NAPFD values for different cycles:")
for cycle, napfd_value in enumerate(NAPFD, start=1):
    print(f"Cycle {cycle}: NAPFD = {napfd_value}")

Cycle = df['Cycle'].unique()

length = df['Cycle'].iloc[-1]

pyplot.plot(Cycle[1:], NAPFD, color='Green', marker='o')
pyplot.title('NAPFD over cycles iofrol', fontsize=14)
pyplot.xlabel('Cycles', fontsize=24)
pyplot.ylabel('NAPFD', fontsize=24)
pyplot.grid(True)
pyplot.gcf().set_size_inches(15, 6)

from statistics import mean
values['Avg NAPFD per cycle'] = mean(NAPFD)

mean(NAPFD)

selected_cycles_df = final_df[(final_df['Cycle'] >= 1) & (final_df['Cycle'] <= 320)]

# Plot the graph
plt.figure(figsize=(12, 6))
sns.lineplot(data=final_df, x='Cycle', y='CalcPrio', marker='o', color='b', linewidth=2)
plt.title('Priority vs. CI Cycle')
plt.xlabel('CI Cycle')
plt.ylabel('Priority')
plt.grid(True)
plt.xticks(rotation=60)
plt.yticks([0, 0.25, 0.50, 0.75, 1.0])  # custom y-axis ticks
plt.tight_layout()
plt.show()

# For pririotized test cases
from datetime import datetime

# Example data
# final_df should contain at least two columns: 'Verdict' and 'ranking'
# 'Verdict' indicates whether a fault is detected (1) or not (0)
# 'ranking' represents the prioritized ranking of test cases

# Start time
start = datetime.now()

# Initialize variables
first_detected = False
first_rank = None
last_rank = None

# Iterate through the rows of final_df
for index, row in final_df.iterrows():
    if row['Verdict'] == 1 and not first_detected:
        # First fault detected
        first_detected = True
        first_rank = row['ranking']
        FT = datetime.now() - start

    if row['Verdict'] == 1:
        # Last fault detected
        last_rank = row['ranking']

# Calculate Last Time (LT) if last_rank is found
if last_rank is not None:
    LT = datetime.now() - start

    # Calculate Average Time (AT)
    AT = (FT + LT) / 2

    print("First Rank:", first_rank)
    print("Last Rank:", last_rank)
    print("Time to Detect First Fault (FT):", FT.total_seconds(), "seconds")
    print("Time to Detect Last Fault (LT):", LT.total_seconds(), "seconds")
    print("Average Time (AT):", AT.total_seconds(), "seconds")
else:
    print("No faults detected.")

startTime = datetime.now()
preparation_time = datetime.now() - startTime
time = pd.DataFrame()
time['Id'] =  range(0, 1)
time['env'] = 'Iofrol'
time['FT'] = FT
time['LT'] = LT
time['AT'] = AT

time

total_time = datetime.now() - startTime


print ("Preparation Time : ",preparation_time)
print ("Pririotization Time : ",prioritization_time)
print ("Total Algorithm Time : ",total_time)
values['Preparation Time'] = preparation_time
values['Pririotization Time'] = prioritization_time
values['Total Algorithm Time'] = total_time


# Convert timedelta to total seconds
preparation_time_seconds = preparation_time.total_seconds()
prioritization_time_seconds = prioritization_time.total_seconds()
total_algorithm_time_seconds = total_time.total_seconds()

# Print the times in a more readable format
print("Preparation Time:", "{:.2f} seconds".format(preparation_time_seconds))
print("Prioritization Time:", "{:.2f} seconds".format(prioritization_time_seconds))
print("Total Algorithm Time:", "{:.2f} seconds".format(total_algorithm_time_seconds))

from sklearn.metrics import confusion_matrix

# Binarize actual and predicted values based on threshold (e.g., 0.5)
threshold = 0.8
y_test_binary = (y_test > threshold).astype(int)
predicted_binary = (model.predict(X_test) > threshold).astype(int)

# Define categories for confusion matrix
categories = ["Fault-Detecting", "No-Fault-Detecting"]

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test_binary, predicted_binary)

# Print confusion matrix
print("Confusion Matrix:")
print("{:<20} {:<20} {:<20}".format("Actual\\Predicted", *categories))
print("-" * 60)
for i, category in enumerate(categories):
    print("{:<20}".format(category), end="")
    for j in range(len(categories)):
        print("{:<20}".format(conf_matrix[i, j]), end="")
    print()

from sklearn.metrics import precision_score, recall_score, f1_score

# Calculate True Positives (TP), True Negatives (TN), False Positives (FP), and False Negatives (FN) from confusion matrix
TP = conf_matrix[0, 0]
TN = conf_matrix[1, 1]
FP = conf_matrix[1, 0]
FN = conf_matrix[0, 1]

# Calculate accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)

# Calculate precision
precision = TP / (TP + FP)

# Calculate recall
recall = TP / (TP + FN)

# Calculate F1 score
f1 = 2 * (precision * recall) / (precision + recall)

# Print accuracy, precision, recall, and F1 score
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

import numpy as np
import matplotlib.pyplot as plt

def plot_confusion_matrix(conf_matrix, classes,
                          normalize=False,  # Changed to False
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        conf_matrix = conf_matrix.astype('float') / conf_matrix.sum(axis=1)[:, np.newaxis]

    plt.imshow(conf_matrix, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = conf_matrix.max() / 2.
    for i in range(conf_matrix.shape[0]):
        for j in range(conf_matrix.shape[1]):
            plt.text(j, i, format(conf_matrix[i, j], fmt),
                     ha="center", va="center",
                     color="white" if conf_matrix[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()

# Define categories for confusion matrix
categories = ["Fault-Detecting", "No-Fault-Detecting"]  # Changed order

# Plot confusion matrix
plt.figure(figsize=(6, 6))
plot_confusion_matrix(conf_matrix, classes=categories, normalize=False, title='Confusion Matrix')
plt.show()

from sklearn.metrics import accuracy_score, precision_recall_curve, roc_curve, roc_auc_score
from sklearn.preprocessing import Binarizer

# Thresholding
threshold = 0.8  # Define the threshold
binarizer = Binarizer(threshold=threshold)
binary_predicted = binarizer.fit_transform(predicted_priority.reshape(-1, 1))

# Calculate metrics
accuracy = accuracy_score(y_test, binary_predicted)
precision, recall, _ = precision_recall_curve(y_test, predicted_priority)
fpr, tpr, _ = roc_curve(y_test, predicted_priority)
auc_roc = roc_auc_score(y_test, predicted_priority)

# Plot ROC Curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='blue', lw=2, label='ROC curve (AUC = %0.2f)' % auc_roc)
plt.plot([0, 1], [0, 1], color='red', lw=1, linestyle='--')
plt.xlim([-0.02, 1.02])  # Adjusted limits
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc='lower right')
plt.show()

# Plot Precision-Recall Curve
plt.figure(figsize=(8, 6))
plt.plot(recall, precision, color='green', lw=2, label='Precision-Recall curve')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend(loc='lower left')
plt.xlim([-0.02, 1.02])  # Adjusted limits
plt.show()

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Assuming final_df contains columns 'cycle', 'actual', and 'predicted'
cycles = final_df['Cycle'].unique()

# Initialize dictionaries to store metrics for each cycle
accuracy_dict = {}
precision_dict = {}
recall_dict = {}

# Iterate over each cycle
for cycle in cycles:
    # Filter DataFrame for the current cycle
    cycle_df = final_df[final_df['Cycle'] == cycle]

    # Binarize actual and predicted values based on threshold (e.g., 0.5)
    threshold = 0.5
    y_actual_binary = (cycle_df['Verdict'] > threshold).astype(int)
    y_predicted_binary = (cycle_df['CalcPrio'] > threshold).astype(int)

    # Calculate confusion matrix
    conf_matrix = confusion_matrix(y_actual_binary, y_predicted_binary)

    # Calculate metrics
    accuracy = accuracy_score(y_actual_binary, y_predicted_binary)
    precision = precision_score(y_actual_binary, y_predicted_binary)
    recall = recall_score(y_actual_binary, y_predicted_binary)

    # Store metrics in dictionaries
    accuracy_dict[cycle] = accuracy
    precision_dict[cycle] = precision
    recall_dict[cycle] = recall

# Print or further analyze the results stored in accuracy_dict, precision_dict, and recall_dict
print("Accuracy for each cycle:")
print(accuracy_dict)
print()
print("Precision for each cycle:")
print(precision_dict)
print()
print("Recall for each cycle:")
print(recall_dict)

import matplotlib.pyplot as plt

# Assuming you have already calculated accuracy_dict, precision_dict, and recall_dict

# Get the last 30 cycles
last_30_cycles = sorted(final_df['Cycle'].unique())[-30:]

# Extract accuracy, precision, and recall for the last 30 cycles
accuracy_last_30 = [accuracy_dict[cycle] for cycle in last_30_cycles]
precision_last_30 = [precision_dict[cycle] for cycle in last_30_cycles]
recall_last_30 = [recall_dict[cycle] for cycle in last_30_cycles]

# Plotting
plt.figure(figsize=(10, 6))

# Accuracy plot
plt.plot(last_30_cycles, accuracy_last_30, label='Accuracy', marker='o', linewidth=1)

# Precision plot
plt.plot(last_30_cycles, precision_last_30, label='Precision', marker='o', linewidth=1)

# Recall plot
plt.plot(last_30_cycles, recall_last_30, label='Recall', marker='o', linewidth=1)

# Adding labels and title
plt.xlabel('Cycle')
plt.ylabel('Metrics Value')
plt.title('Accuracy, Precision, and Recall for Last 30 Cycles')
plt.legend()

# Adding grid lines in dotted style
plt.grid(True, linestyle='--')

# Show plot
plt.show()





